name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Pull Docker image from dockerhub
        run: sudo docker pull aneesha95/dockerec2:latest

      - name: Delete the old docker container
        run: sudo docker rm -f dockerec2-container || true

      - name: Run the docker container
        run: sudo docker run -d -p 80:80 --name dockerec2-container aneesha95/dockerec2
